#!/bin/bash

alias pushd="pushd >> /dev/null"
alias popd="popd >> /dev/null"

echo "Instalowanie vim-plug"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

pushd ~

echo "Linkowanie wszystkich plików"

for file in bin .fonts .icons .themes .tmux.conf .xinitrc .Xresources .zshrc .zshrc .offlineimap.py .offlineimaprc .mailcap .msmtprc; do
	ln -sf ~/dotfiles/$file
done

popd
pushd ~/.config

for file in ./.config/*; do
	ln -sf ~/dotfiles/.config/$file
done

popd

echo "Instalowanie wszystkich pakietów"
yay -S --needed --noconfirm $(cat packages)

