#!/bin/bash

files=("bin" ".zshrc" ".tmux.conf" ".config/i3" ".config/polybar" ".tmuxrc" ".config/nvim")

yay -Sy --needed git zsh neovim || exit 1

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

pushd ~
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf

for file in $files; do
	ln -fs ~/dotfiles/$file $file
done

popd

yay -S --needed --noedit --noconfirm $(cat packages)

